# git aliases
alias gf='git fetch';
alias gr='git reset';
alias grs='git reset --soft';
alias grh='git reset --hard';
alias gro='git reset --hard origin/`git symbolic-ref --short HEAD`'
alias grb='git rebase -i';
alias grbo='git rebase -i origin/`git symbolic-ref --short HEAD`';
alias grbm='git rebase -i origin/master';
alias grbd='git rebase -i origin/dev';
alias gcp='git cherry-pick';
alias gm='git merge';
alias gmf='git merge --ff-only';
alias gmo='git merge origin/`git symbolic-ref --short HEAD`';
alias gmm='git merge origin/master';
alias gmd='git merge origin/dev';
alias gmof='git merge --ff-only origin/`git symbolic-ref --short HEAD`';
alias gmmf='git merge --ff-only origin/master';
alias gmdf='git merge --ff-only origin/dev';
alias gd='git diff';
alias gds='git diff --staged';
# alias gdc='git diff --cached'; // same as --staged
alias gch='git checkout';
alias gchm='git checkout master';
alias gchd='git checkout dev';
alias gci='git commit -m ';
alias gcia='git commit --amend';
alias gs='git status';
alias gsi='git status --ignored';
alias gsif='git ls-files --other --ignored --exclude-standard';
alias gsh='git show';
alias gl='git log --pretty=format:"%h | %cd | %s%d [%cn]%n" --date=short';
alias glg='git log --pretty=format:"%h | %cd | %s%d [%cn]%n" --date=short --graph';
alias gll='git log --pretty=format:"%h | %cd | %s%d [%cn]%n" --date=short -20';
alias gllg='git log --pretty=format:"%h | %cd | %s%d [%cn]%n" --date=short -20 --graph';
alias gld='git log --pretty=format:"%h | %cd [%cn]%n%s%d%n" --date=iso --name-status';
# alias gl='git log --pretty=format:"%h | %cd | %s%d [%cn]" --date=short';
# alias glg='git log --pretty=format:"%h | %cd | %s%d [%cn]" --date=short --graph';
# alias gll='git log --pretty=format:"%h | %cd | %s%d [%cn]" --date=short -20';
# alias gllg='git log --pretty=format:"%h | %cd | %s%d [%cn]" --date=short -20 --graph';
# alias gld='git log --pretty=format:"%h | %cd [%cn]%n%s%d%n" --date=iso --name-status';
alias ga='git add -i';
alias gap='git add -p';
alias gau='git add -u';
alias gaa='git add --all';
alias gst='git stash';
alias gstl='git stash list';
alias gstk='git stash --keep-index';
alias gstu='git stash --include-untracked';
alias gstall='git stash --all';
alias gsta='git stash apply';
alias gstp='git stash pop';
alias gbr='git branch';
alias gbrt='git branch -vv';
alias gmt='git mergetool';
alias gdt='git difftool';
alias grf='git reflog';
