MERGE_TOOL=code;
DIFF_TOOL=kdiff3.exe;

MERGED=$1;
LOCAL=$2;
BASE=$3;
REMOTE=$4;

$DIFF_TOOL $BASE $LOCAL -L1 "BASE: $BASE" -L2 "LOCAL: $LOCAL" &
$DIFF_TOOL $BASE $REMOTE -L1 "BASE: $BASE" -L2 "REMOTE: $REMOTE"  &
$MERGE_TOOL -r -d $BASE $LOCAL &
$MERGE_TOOL -r -d $BASE $REMOTE &
$MERGE_TOOL -r $MERGED
# $MERGE_TOOL -r -d $REMOTE $MERGED
