MERGE_TOOL=C:/dev/tools/diff/KDiff3/kdiff3.exe;

MERGED=$1;
LOCAL=$2;
BASE=$3;
REMOTE=$4;

$MERGE_TOOL $BASE $LOCAL -L1 "BASE: $BASE" -L2 "LOCAL: $LOCAL" &
$MERGE_TOOL $BASE $REMOTE -L1 "BASE: $BASE" -L2 "REMOTE: $REMOTE"  &
$MERGE_TOOL $BASE $LOCAL $REMOTE --merge --output $MERGED -L1 "BASE: $BASE" -L2 "LOCAL: $LOCAL" -L3 "REMOTE: $REMOTE"
# no auto conflict resolve
# $MERGE_TOOL $BASE $LOCAL $REMOTE --qall --output $MERGED -L1 "BASE: $BASE" -L2 "LOCAL: $LOCAL" -L3 "REMOTE: $REMOTE"
